### ISSUE TITLE
Doesn't support basic auth of alertmanager.url?

### ISSUE THREAD

**Issue by kkitai** [frodenas/alertmanager-resource#4]
Hi.

My alertmanager is set to be using basic auth and I setup pipeline as following:

```
jobs:
- name: job-hello-world
  public: true
  plan:
  - get: time
    trigger: true
  - put: silence-test-alerts
    resource: am
    params:
      operation: silence
      matchers: "service=cf"
      expires: 30m

resources:
- name: am
  type: alertmanager-resource
  source:
    url: http://admin:password@172.21.185.33:9093/
- name: time
  type: time
  source:
    interval: 1m
    
resource_types :
- name: alertmanager-resource
  type: docker-image
  source:
    repository: frodenas/alertmanager-resource
```

but concourse(amtool) prints error.

```
0e207f34e107: Pull complete
154c7d3824e9: Pull complete
d1fdece7f9a9: Pull complete
Digest: sha256:64d9a5163223cedb990a20e07fa171aaf9e90925ddea5d55a62732ead65745cd
Status: Downloaded newer image for frodenas/alertmanager-resource@sha256:64d9a5163223cedb990a20e07fa171aaf9e90925ddea5d55a62732ead65745cd

Successfully pulled frodenas/alertmanager-resource@sha256:64d9a5163223cedb990a20e07fa171aaf9e90925ddea5d55a62732ead65745cd.

amtool: error: Get http://172.21.185.33:9093/api/v1/silences?filter=: dial tcp 172.21.185.33:9093: getsockopt: connection refused
```

I can get a response successfully by curl.

```
$ curl http://admin:password@172.21.185.33:9093/api/v1/silences
{"status":"success","data":[]}
```

**Comment by kkitai** [comment]
It did work with 

```
resources:
- name: am
  type: alertmanager-resource
  source:
    url: http://admin:password@172.21.185.33:9093   # if there is / at end, it doesn't work
```

```

comment | Silence added by CI pipeline http://172.21.185.13/teams/main/pipelines/alert-manager-pipeline/jobs/job-hello-world/builds/6
-- | --
created_by |  
ends_at | 2018-05-18T04:39:06.110679986Z
starts_at | 2018-05-18T04:09:06.11522511Z
updated_at | 2018-05-18T04:09:06.115243322Z

```
